import {Buffer} from "buffer";

export const OWNER_OFFSET = 0;
export const OPEN_OFFSET = 64;
export const TROVE_OPEN = new Buffer([1]);

export enum TROVE_PROGRAM_INSTRUCTION {CREATE, UPDATE, LIQUIDATE, CLOSE, REDEMPTION}

export const TROVE_CREATE_INSTRUCTION = new Buffer([TROVE_PROGRAM_INSTRUCTION.CREATE]);
export const TROVE_UPDATE_INSTRUCTION = new Buffer([TROVE_PROGRAM_INSTRUCTION.UPDATE]);
export const TROVE_LIQUIDATE_INSTRUCTION = new Buffer([TROVE_PROGRAM_INSTRUCTION.LIQUIDATE]);
export const TROVE_CLOSE_INSTRUCTION = new Buffer([TROVE_PROGRAM_INSTRUCTION.CLOSE]);
export const REDEMPTION_INSTRUCTION = new Buffer([TROVE_PROGRAM_INSTRUCTION.REDEMPTION]);
