import {Buffer} from "buffer";

export const OWNER_OFFSET = 0;
export const AMOUNT_OFFSET = 32;
export const OPEN_OFFSET = 40;
export const STABILITY_POOL_OPEN = new Buffer([1]);

export enum STABILITY_POOL_PROGRAM_INSTRUCTION {CREATE, UPDATE,BURN=4}

export const STABILITY_POOL_CREATE_INSTRUCTION = new Buffer([STABILITY_POOL_PROGRAM_INSTRUCTION.CREATE]);
export const STABILITY_POOL_UPDATE_INSTRUCTION = new Buffer([STABILITY_POOL_PROGRAM_INSTRUCTION.UPDATE]);
